# Generated by Django 4.2.16 on 2025-12-26 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rental_end_date',
            field=models.DateField(blank=True, help_text='Latest date this product can be returned. Leave empty for no restriction.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rental_start_date',
            field=models.DateField(blank=True, help_text='Earliest date this product can be rented from. Leave empty for no restriction.', null=True),
        ),
        migrations.CreateModel(
            name='RentalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('rental_start_date', models.DateField()),
                ('return_date', models.DateField()),
                ('is_returned', models.BooleanField(default=False)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('overdue_notification_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_records', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_record', to='orders.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_records', to='core.product')),
            ],
            options={
                'verbose_name': 'Rental Record',
                'verbose_name_plural': 'Rental Records',
                'ordering': ['-rental_start_date', '-created_at'],
            },
        ),
    ]
