# Generated by Django 4.2.16 on 2026-01-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_rental_products',
            field=models.ManyToManyField(blank=True, help_text='Select rental products that can be paired with this selling product.', limit_choices_to={'selling_type': 'rental'}, related_name='related_selling_products', to='core.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_type',
            field=models.CharField(choices=[('rental', 'Rental'), ('selling', 'Selling')], default='rental', help_text='Rental: clients rent for a period. Selling: clients buy permanently.', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='rental_end_date',
            field=models.DateField(blank=True, help_text='Latest date this product can be returned. Leave empty for no restriction. (Only for rental products)', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rental_start_date',
            field=models.DateField(blank=True, help_text='Earliest date this product can be rented from. Leave empty for no restriction. (Only for rental products)', null=True),
        ),
    ]
