# Generated by Django 4.2.16 on 2026-01-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_selling_type_to_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btw_percentage', models.DecimalField(decimal_places=2, default=21.0, help_text='BTW (VAT) percentage', max_digits=5)),
                ('btw_type', models.CharField(choices=[('inclusif', 'Inclusif (BTW included in prices)'), ('exclusif', 'Exclusif (BTW added to prices)')], default='inclusif', help_text='Whether BTW is included in prices or added separately', max_length=10)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery/shipping cost', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Costs Settings',
                'verbose_name_plural': 'Costs Settings',
            },
        ),
    ]
