# Generated by Django 4.2.16 on 2026-01-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='costs',
            name='delivery_cost_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable delivery cost'),
        ),
    ]
