# Generated by Django 4.2.16 on 2026-01-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, max_length=200)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('mollie_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('mollie_checkout_url', models.URLField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='open', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message from supporter')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Support',
                'verbose_name_plural': 'Supports',
                'ordering': ['-created_at'],
            },
        ),
    ]
